spring:
  datasource:
    name: mysql
    url: jdbc:mysql://127.0.0.1:3306/commontest?useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: cn.gs.entity  # 注意：对应实体类的路径\

logging:
  level:
    cn.gs.mapper: debug
server:
  port: 9900

#management:
#  security:
#    enabled: false
