spring:
  thymeleaf:
    cache: false
  datasource:
    name: mysql
    url: jdbc:mysql://127.0.0.1:3306/commontest?useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-open-prepared-statements: 20
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: select 'x'
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-idle: 1
      max-wait-millis: 60000
      initial-size: 1
    tomcat:
      max-active: 20

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: cn.gs.entity  # 注意：对应实体类的路径\

logging:
  level:
    cn.gs.mapper: debug
server:
  port: 9900

#management:
#  security:
#    enabled: false
